/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class julianwi_awtpeer_AndroidGraphics2D */

#ifndef _Included_julianwi_awtpeer_AndroidGraphics2D
#define _Included_julianwi_awtpeer_AndroidGraphics2D
#ifdef __cplusplus
extern "C" {
#endif
#undef julianwi_awtpeer_AndroidGraphics2D_INTERPOLATION_NEAREST
#define julianwi_awtpeer_AndroidGraphics2D_INTERPOLATION_NEAREST 0L
#undef julianwi_awtpeer_AndroidGraphics2D_INTERPOLATION_BILINEAR
#define julianwi_awtpeer_AndroidGraphics2D_INTERPOLATION_BILINEAR 1L
#undef julianwi_awtpeer_AndroidGraphics2D_INTERPOLATION_BICUBIC
#define julianwi_awtpeer_AndroidGraphics2D_INTERPOLATION_BICUBIC 5L
#undef julianwi_awtpeer_AndroidGraphics2D_ALPHA_INTERPOLATION_SPEED
#define julianwi_awtpeer_AndroidGraphics2D_ALPHA_INTERPOLATION_SPEED 2L
#undef julianwi_awtpeer_AndroidGraphics2D_ALPHA_INTERPOLATION_QUALITY
#define julianwi_awtpeer_AndroidGraphics2D_ALPHA_INTERPOLATION_QUALITY 3L
#undef julianwi_awtpeer_AndroidGraphics2D_ALPHA_INTERPOLATION_DEFAULT
#define julianwi_awtpeer_AndroidGraphics2D_ALPHA_INTERPOLATION_DEFAULT 4L
/*
 * Class:     julianwi_awtpeer_AndroidGraphics2D
 * Method:    directraster
 * Signature: (Ljava/nio/ByteBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_julianwi_awtpeer_AndroidGraphics2D_directraster
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     julianwi_awtpeer_AndroidGraphics2D
 * Method:    cairoDrawString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_julianwi_awtpeer_AndroidGraphics2D_cairoDrawString
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     julianwi_awtpeer_AndroidGraphics2D
 * Method:    cairoDrawImage
 * Signature: (JLjava/nio/ByteBuffer;IIII)V
 */
JNIEXPORT void JNICALL Java_julianwi_awtpeer_AndroidGraphics2D_cairoDrawImage
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
