/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class julianwi_awtpeer_FreetypeFontPeer */

#ifndef _Included_julianwi_awtpeer_FreetypeFontPeer
#define _Included_julianwi_awtpeer_FreetypeFontPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     julianwi_awtpeer_FreetypeFontPeer
 * Method:    InitFreeType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_julianwi_awtpeer_FreetypeFontPeer_InitFreeType
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
