/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class julianwi_awtpeer_FreetypeFontPeer */

#ifndef _Included_julianwi_awtpeer_FreetypeFontPeer
#define _Included_julianwi_awtpeer_FreetypeFontPeer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     julianwi_awtpeer_FreetypeFontPeer
 * Method:    initFreeType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_julianwi_awtpeer_FreetypeFontPeer_initFreeType
  (JNIEnv *, jclass);

/*
 * Class:     julianwi_awtpeer_FreetypeFontPeer
 * Method:    createfont
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_julianwi_awtpeer_FreetypeFontPeer_createfont
  (JNIEnv *, jobject);

/*
 * Class:     julianwi_awtpeer_FreetypeFontPeer
 * Method:    initFont
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_julianwi_awtpeer_FreetypeFontPeer_initFont
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     julianwi_awtpeer_FreetypeFontPeer
 * Method:    setsize
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_julianwi_awtpeer_FreetypeFontPeer_setsize
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
