/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class julianwi_awtpeer_WindowActivity */

#ifndef _Included_julianwi_awtpeer_WindowActivity
#define _Included_julianwi_awtpeer_WindowActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     julianwi_awtpeer_WindowActivity
 * Method:    createsock
 * Signature: ()Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_julianwi_awtpeer_WindowActivity_createsock
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
