/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class julianwi_awtpeer_ListenerOldApi */

#ifndef _Included_julianwi_awtpeer_ListenerOldApi
#define _Included_julianwi_awtpeer_ListenerOldApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     julianwi_awtpeer_ListenerOldApi
 * Method:    listsocket
 * Signature: (Landroid/view/Surface;Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL Java_julianwi_awtpeer_ListenerOldApi_listsocket
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
